#The chance of updating the player's temperature when they are freezing
#Range: 0.0 ~ 1.0
updateChanceFreezing = 0.07999999821186066
#The chance of updating the player's temperature when they are on fire
#Range: 0.0 ~ 1.0
updateChanceFire = 0.07999999821186066
#The chance of updating the player's temperature when they are in lava
#Range: 0.0 ~ 1.0
updateChanceLava = 0.15000000596046448
#The chance of updating the player's temperature when they are in a normal environment
#Range: 0.0 ~ 1.0
updateChanceDefault = 0.004999999888241291
#Defines how close to the environment temperature the player temp has to be to snap to the target temperature
#Range: 0.0 ~ 60.0
tempDifferenceSnap = 1.0
#Defines how quickly the player temperature adjusts to the environment temperature
#Range: 0.0 ~ 2.5
tempAdjustmentSpeed = 0.6000000238418579

